const UserListDummy = [
  {
    user_id: 1,
    user_fullname: 'Ani',
    user_phone: '08192091210',
    user_email: 'ani@gmail.com',
    user_address: 'Jalan Pegangsaan Raya No.19, Jakarta Selatan',
    user_password: 'Password1',
  },
  {
    user_id: 2,
    user_fullname: 'Budi Satria',
    user_phone: '08192091221',
    user_email: 'budisatria@gmail.com',
    user_address: 'Jalan Damai Raya No.12, Jakarta Utara',
    user_password: 'Password1',
  },
  {
    user_id: 3,
    user_fullname: 'Citra Wardhani',
    user_phone: '08112091221',
    user_email: 'citra@gmail.com',
    user_address: 'Jalan Alumununium Blok C No.31, Jakarta Selatan',
    user_password: 'Password1',
  },
  {
    user_id: 4,
    user_fullname: 'Dandi Wjiaya',
    user_phone: '08131920121',
    user_email: 'dandiwijaya@gmail.com',
    user_address: 'Jalan Perak Blok F No.19, Jakarta Selatan',
    user_password: 'Password1',
  },
  {
    user_id: 5,
    user_fullname: 'Eka Satria',
    user_phone: '08561920126',
    user_email: 'eka@gmail.com',
    user_address: 'Jalan Juraganan No.17, Jakarta Selatan',
    user_password: 'Password1',
  },
  {
    user_id: 6,
    user_fullname: 'Aji',
    user_phone: '08112091210',
    user_email: 'aji@gmail.com',
    user_address: 'Jalan Merak Raya No.19, Jakarta Selatan',
    user_password: 'Password1',
  },
  {
    user_id: 7,
    user_fullname: 'Budi Doremi',
    user_phone: '08292099421',
    user_email: 'budi@gmail.com',
    user_address: 'Jalan Bekasi Raya No.12, Jakarta Utara',
    user_password: 'Password1',
  },
  {
    user_id: 8,
    user_fullname: 'Jaka',
    user_phone: '08145291221',
    user_email: 'jaka@gmail.com',
    user_address: 'Jalan Merah Delima Blok C No.31, Jakarta Selatan',
    user_password: 'Password1',
  },
  {
    user_id: 9,
    user_fullname: 'Gradisca',
    user_phone: '08838920121',
    user_email: 'grad@gmail.com',
    user_address: 'Komplek DPR Blok F No.19, Jakarta Selatan',
    user_password: 'Password1',
  },
  {
    user_id: 10,
    user_fullname: 'Satria',
    user_phone: '08599820126',
    user_email: 'satria@gmail.com',
    user_address: 'Jalan Blue Hills No.17, Jakarta Selatan',
    user_password: 'Password1',
  },
  {
    user_id: 11,
    user_fullname: 'Benny',
    user_phone: '08830900121',
    user_email: 'benny@gmail.com',
    user_address: 'Komplek DPR Blok G No.19, Jakarta Selatan',
    user_password: 'Password1',
  },
  {
    user_id: 12,
    user_fullname: 'Jony',
    user_phone: '08599765126',
    user_email: 'jjony@gmail.com',
    user_address: 'Jalan Pahlawan No.17, Jakarta Selatan',
    user_password: 'Password1',
  },
];

export default UserListDummy;
